import Fuzz "./src";
import Debug "mo:base/Debug";

let fuzz = Fuzz.Fuzz();

Debug.print(debug_show "----------------- nat8 range 0-5 -------------------");
Debug.print(debug_show fuzz.nat8.randomRange(0, 5));
Debug.print(debug_show fuzz.nat8.randomRange(0, 5));
Debug.print(debug_show fuzz.nat8.randomRange(0, 5));
Debug.print(debug_show fuzz.nat8.randomRange(0, 5));
Debug.print(debug_show fuzz.nat8.randomRange(0, 5));
Debug.print(debug_show fuzz.nat8.randomRange(0, 5));
Debug.print(debug_show fuzz.nat8.randomRange(0, 5));
Debug.print(debug_show fuzz.nat8.randomRange(0, 5));
Debug.print(debug_show fuzz.nat8.randomRange(0, 5));

Debug.print(debug_show "----------------- nat -------------------");
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat8.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat16.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat32.random());
Debug.print(debug_show fuzz.nat64.random());
Debug.print(debug_show fuzz.nat64.random());
Debug.print(debug_show fuzz.nat64.random());
Debug.print(debug_show fuzz.nat64.random());
Debug.print(debug_show fuzz.nat64.random());
Debug.print(debug_show fuzz.nat64.random());
Debug.print(debug_show fuzz.nat64.random());
Debug.print(debug_show fuzz.nat64.random());
Debug.print(debug_show fuzz.nat64.random());
Debug.print(debug_show fuzz.nat64.random());
Debug.print(debug_show fuzz.nat64.random());
Debug.print(debug_show fuzz.nat64.random());
Debug.print(debug_show fuzz.nat64.random());
Debug.print(debug_show fuzz.nat64.random());
Debug.print(debug_show fuzz.nat64.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.random());
Debug.print(debug_show fuzz.nat.randomRange(2**512, 2**1024));

Debug.print(debug_show "----------------- int -------------------");
Debug.print(debug_show fuzz.int8.random());
Debug.print(debug_show fuzz.int8.random());
Debug.print(debug_show fuzz.int8.random());
Debug.print(debug_show fuzz.int8.random());
Debug.print(debug_show fuzz.int8.random());
Debug.print(debug_show fuzz.int8.random());
Debug.print(debug_show fuzz.int8.random());
Debug.print(debug_show fuzz.int16.random());
Debug.print(debug_show fuzz.int16.random());
Debug.print(debug_show fuzz.int16.random());
Debug.print(debug_show fuzz.int16.random());
Debug.print(debug_show fuzz.int16.random());
Debug.print(debug_show fuzz.int16.random());
Debug.print(debug_show fuzz.int16.random());
Debug.print(debug_show fuzz.int32.random());
Debug.print(debug_show fuzz.int32.random());
Debug.print(debug_show fuzz.int32.random());
Debug.print(debug_show fuzz.int32.random());
Debug.print(debug_show fuzz.int32.random());
Debug.print(debug_show fuzz.int32.random());
Debug.print(debug_show fuzz.int64.random());
Debug.print(debug_show fuzz.int64.random());
Debug.print(debug_show fuzz.int64.random());
Debug.print(debug_show fuzz.int64.random());
Debug.print(debug_show fuzz.int64.random());
Debug.print(debug_show fuzz.int.random());
Debug.print(debug_show fuzz.int.random());
Debug.print(debug_show fuzz.int.random());
Debug.print(debug_show fuzz.int.random());

Debug.print(debug_show "------------------- float -------------------");
Debug.print(debug_show fuzz.float.random());
Debug.print(debug_show fuzz.float.random());
Debug.print(debug_show fuzz.float.random());
Debug.print(debug_show fuzz.float.random());
Debug.print(debug_show fuzz.float.random());
Debug.print(debug_show fuzz.float.random());

Debug.print(debug_show "------------------- float.randomRange -------------------");
Debug.print(debug_show fuzz.float.randomRange(0.5, 0.7));
Debug.print(debug_show fuzz.float.randomRange(0.5, 0.7));
Debug.print(debug_show fuzz.float.randomRange(0.5, 0.7));
Debug.print(debug_show fuzz.float.randomRange(0.5, 0.7));
Debug.print(debug_show fuzz.float.randomRange(0.5, 0.7));
Debug.print(debug_show fuzz.float.randomRange(0.5, 0.7));
Debug.print(debug_show fuzz.float.randomRange(0.5, 0.7));
Debug.print(debug_show fuzz.float.randomRange(0.5, 0.7));
Debug.print(debug_show fuzz.float.randomRange(0.5, 0.7));
Debug.print(debug_show fuzz.float.randomRange(0.5, 0.7));
Debug.print(debug_show fuzz.float.randomRange(0.5, 0.7));
Debug.print(debug_show fuzz.float.randomRange(0.5, 0.7));
Debug.print(debug_show fuzz.float.randomRange(0.5, 0.7));
Debug.print(debug_show fuzz.float.randomRange(0.5, 0.7));

Debug.print(debug_show "------------------- array -------------------");
Debug.print(debug_show fuzz.array.randomArray(10, fuzz.nat8.random));
Debug.print(debug_show fuzz.array.randomArray(10, fuzz.nat32.random));
type MyType = {
	x: Nat8;
	b: Bool;
};
let randArray = fuzz.array.randomArray<MyType>(10, func() {
	return {
		x = fuzz.nat8.random();
		b = fuzz.bool.random();
	};
});

Debug.print(debug_show randArray);

Debug.print(debug_show "------------------- bool -------------------");
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());
Debug.print(debug_show fuzz.bool.random());

Debug.print(debug_show "------------------- char.randomAlphabetic -------------------");
Debug.print(debug_show fuzz.char.randomAlphabetic());
Debug.print(debug_show fuzz.char.randomAlphabetic());
Debug.print(debug_show fuzz.char.randomAlphabetic());
Debug.print(debug_show fuzz.char.randomAlphabetic());
Debug.print(debug_show fuzz.char.randomAlphabetic());
Debug.print(debug_show fuzz.char.randomAlphabetic());
Debug.print(debug_show fuzz.char.randomAlphabetic());
Debug.print(debug_show fuzz.char.randomAlphabetic());
Debug.print(debug_show fuzz.char.randomAlphabetic());

Debug.print(debug_show "------------------- char.randomAlphanumeric -------------------");
Debug.print(debug_show fuzz.char.randomAlphanumeric());
Debug.print(debug_show fuzz.char.randomAlphanumeric());
Debug.print(debug_show fuzz.char.randomAlphanumeric());
Debug.print(debug_show fuzz.char.randomAlphanumeric());
Debug.print(debug_show fuzz.char.randomAlphanumeric());
Debug.print(debug_show fuzz.char.randomAlphanumeric());
Debug.print(debug_show fuzz.char.randomAlphanumeric());
Debug.print(debug_show fuzz.char.randomAlphanumeric());
Debug.print(debug_show fuzz.char.randomAlphanumeric());

Debug.print(debug_show "------------------- char.randomAscii -------------------");
Debug.print(debug_show fuzz.char.randomAscii());
Debug.print(debug_show fuzz.char.randomAscii());
Debug.print(debug_show fuzz.char.randomAscii());
Debug.print(debug_show fuzz.char.randomAscii());
Debug.print(debug_show fuzz.char.randomAscii());
Debug.print(debug_show fuzz.char.randomAscii());
Debug.print(debug_show fuzz.char.randomAscii());
Debug.print(debug_show fuzz.char.randomAscii());
Debug.print(debug_show fuzz.char.randomAscii());

Debug.print(debug_show "------------------- char.randomUnicode -------------------");
Debug.print(debug_show fuzz.char.randomUnicode(['%', 'x', '#', 'y']));
Debug.print(debug_show fuzz.char.randomUnicode(['%', 'x', '#', 'y']));
Debug.print(debug_show fuzz.char.randomUnicode(['%', 'x', '#', 'y']));
Debug.print(debug_show fuzz.char.randomUnicode(['%', 'x', '#', 'y']));
Debug.print(debug_show fuzz.char.randomUnicode(['%', 'x', '#', 'y']));
Debug.print(debug_show fuzz.char.randomUnicode(['%', 'x', '#', 'y']));
Debug.print(debug_show fuzz.char.randomUnicode(['%', 'x', '#', 'y']));
Debug.print(debug_show fuzz.char.randomUnicode(['%', 'x', '#', 'y']));
Debug.print(debug_show fuzz.char.randomUnicode(['%', 'x', '#', 'y']));
Debug.print(debug_show fuzz.char.randomUnicode(['%', 'x', '#', 'y']));
Debug.print(debug_show fuzz.char.randomUnicode(['%', 'x', '#', 'y']));
Debug.print(debug_show fuzz.char.randomUnicode(['%', 'x', '#', 'y']));

Debug.print(debug_show "------------------- text.randomAlphabetic -------------------");
Debug.print(debug_show fuzz.text.randomAlphabetic(20));
Debug.print(debug_show fuzz.text.randomAlphabetic(20));
Debug.print(debug_show fuzz.text.randomAlphabetic(20));
Debug.print(debug_show fuzz.text.randomAlphabetic(20));
Debug.print(debug_show fuzz.text.randomAlphabetic(20));
Debug.print(debug_show fuzz.text.randomAlphabetic(20));
Debug.print(debug_show fuzz.text.randomAlphabetic(20));
Debug.print(debug_show fuzz.text.randomAlphabetic(20));
Debug.print(debug_show fuzz.text.randomAlphabetic(20));

Debug.print(debug_show "------------------- text.randomAlphanumeric -------------------");
Debug.print(debug_show fuzz.text.randomAlphanumeric(33));
Debug.print(debug_show fuzz.text.randomAlphanumeric(33));
Debug.print(debug_show fuzz.text.randomAlphanumeric(33));
Debug.print(debug_show fuzz.text.randomAlphanumeric(33));
Debug.print(debug_show fuzz.text.randomAlphanumeric(33));
Debug.print(debug_show fuzz.text.randomAlphanumeric(33));
Debug.print(debug_show fuzz.text.randomAlphanumeric(33));
Debug.print(debug_show fuzz.text.randomAlphanumeric(33));
Debug.print(debug_show fuzz.text.randomAlphanumeric(33));

Debug.print(debug_show "------------------- text.randomAscii -------------------");
Debug.print(debug_show fuzz.text.randomAscii(44));
Debug.print(debug_show fuzz.text.randomAscii(44));
Debug.print(debug_show fuzz.text.randomAscii(44));
Debug.print(debug_show fuzz.text.randomAscii(44));
Debug.print(debug_show fuzz.text.randomAscii(44));
Debug.print(debug_show fuzz.text.randomAscii(44));
Debug.print(debug_show fuzz.text.randomAscii(44));
Debug.print(debug_show fuzz.text.randomAscii(44));
Debug.print(debug_show fuzz.text.randomAscii(44));

Debug.print(debug_show "------------------- text.randomText -------------------");
Debug.print(debug_show fuzz.text.randomText(fuzz.nat.randomRange(0, 100)));
Debug.print(debug_show fuzz.text.randomText(fuzz.nat.randomRange(0, 100)));
Debug.print(debug_show fuzz.text.randomText(fuzz.nat.randomRange(0, 100)));
Debug.print(debug_show fuzz.text.randomText(fuzz.nat.randomRange(0, 100)));
Debug.print(debug_show fuzz.text.randomText(fuzz.nat.randomRange(0, 100)));
Debug.print(debug_show fuzz.text.randomText(fuzz.nat.randomRange(0, 100)));
Debug.print(debug_show fuzz.text.randomText(fuzz.nat.randomRange(0, 100)));
Debug.print(debug_show fuzz.text.randomText(fuzz.nat.randomRange(0, 100)));
Debug.print(debug_show fuzz.text.randomText(fuzz.nat.randomRange(0, 100)));

Debug.print(debug_show "------------------- blob.randomBlob -------------------");
Debug.print(debug_show fuzz.blob.randomBlob(10));
Debug.print(debug_show fuzz.blob.randomBlob(10));
Debug.print(debug_show fuzz.blob.randomBlob(10));

Debug.print(debug_show "------------------- principal.randomPrincipal -------------------");
Debug.print(debug_show fuzz.principal.randomPrincipal(10));
Debug.print(debug_show fuzz.principal.randomPrincipal(10));
Debug.print(debug_show fuzz.principal.randomPrincipal(20));
Debug.print(debug_show fuzz.principal.randomPrincipal(20));
Debug.print(debug_show fuzz.principal.randomPrincipal(50));
Debug.print(debug_show fuzz.principal.randomPrincipal(50));